server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: developer
    url: jdbc:mysql://localhost:3306/code_buffer_db
    password: 1234567
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Bem vindo a Daily Code Buffer!